# Generated by Django 4.2.7 on 2026-02-20 21:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='min_capital_plan_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum amount for capital plan investments', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_crypto_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum amount for crypto investments', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='min_real_estate_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum amount for real estate investments', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
