# Generated by Django 4.2.7 on 2026-02-22 22:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_platformsettings_min_capital_plan_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='capital_advance_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='Minimum investment for Advance capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='capital_basic_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum investment for Basic capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='capital_standard_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Minimum investment for Standard capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='real_estate_luxury_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('20000.00'), help_text='Minimum investment for Luxury Estate', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='real_estate_premium_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Minimum investment for Premium Property', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='real_estate_starter_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum investment for Starter Property', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
