# Generated by Django 6.0.3 on 2026-03-11 00:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_platformsettings_capital_advance_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='capital_advance_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum investment for Advance capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='capital_basic_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Minimum investment for Basic capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='capital_standard_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Minimum investment for Standard capital plan', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
