# Generated by Django 4.2.7 on 2026-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_usdtdepositrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('profit', 'Profit'), ('referral_bonus', 'Referral Bonus'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit')], max_length=20),
        ),
    ]
