# Generated by Django 4.2.7 on 2026-02-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_admin_crypto_prices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admincryptoprice',
            new_name='investments_coin_551743_idx',
            old_name='investments_coin_idx',
        ),
        migrations.RenameIndex(
            model_name='admincryptoprice',
            new_name='investments_is_acti_3f1c65_idx',
            old_name='investments_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='cryptopricehistory',
            new_name='investments_coin_b7138e_idx',
            old_name='investments_coin_created_idx',
        ),
    ]
