# Generated by Django 6.0.3 on 2026-03-11 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseEdgeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('win_streak_3_reduction', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('win_streak_5_reduction', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('high_amount_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('high_amount_reduction', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('very_high_amount_threshold', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('very_high_amount_reduction', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('high_profit_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('high_profit_reduction', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('strike_price_adjustment', models.DecimalField(decimal_places=4, default=0.001, max_digits=5)),
                ('min_delay_ms', models.IntegerField(default=100)),
                ('max_delay_ms', models.IntegerField(default=500)),
                ('max_open_trades_per_user', models.IntegerField(default=10)),
                ('max_exposure_per_asset', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('max_total_exposure', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('commodity', 'Commodity'), ('stock', 'Stock')], max_length=20)),
                ('base_payout', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=4, default=0.005, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('min_trade_amount', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
                ('max_trade_amount', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='UserTradingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('current_win_streak', models.IntegerField(default=0)),
                ('current_loss_streak', models.IntegerField(default=0)),
                ('max_win_streak', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinaryTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('buy', 'Buy/Call'), ('sell', 'Sell/Put')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('strike_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('final_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('base_payout_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adjusted_payout_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('house_edge_applied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry_seconds', models.IntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('execution_delay_ms', models.IntegerField(default=0)),
                ('user_win_streak', models.IntegerField(default=0)),
                ('user_total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binary_trades', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='binary_trading.tradingasset')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='binary_trad_user_id_59fe3e_idx'), models.Index(fields=['expires_at'], name='binary_trad_expires_33deb6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='binary_trading.tradingasset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='binary_trad_asset_i_67368d_idx')],
            },
        ),
    ]
