# Generated by Django 6.0.3 on 2026-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binary_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binarytrade',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
